<div class="col-lg-6 marg30">
    <div class="well bs-component wellbox">
        <form class="form-horizontal">
            <fieldset>
                <legend>Форма сброса счетчика
                    <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>" class="btn btn-primary btn-xs clear">Назад к Ленте новостей</a> 
                </legend>
                <div class="form-group">
                    <label for="inputEmail" class="col-lg-2 control-label">Название Новости</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="focusedInput" placeholder="Введите название новости ...">
                    </div>
                </div>                  
                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <button type="submit" class="btn btn-primary">Сбросить</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>